include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    unnecessary_this: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
