name: habitatu
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  dartz: ^0.10.0-nullsafety.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.3
  equatable: ^2.0.2
  cloud_firestore: ^2.2.0
  connectivity: ^3.0.4
  data_connection_checker: ^0.3.4
  sizer: ^2.0.13
  flutter_form_builder: ^6.0.1
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  build_runner: ^2.0.3
  get_it: ^7.1.3
  flutter_signin_button: ^2.0.0
  flutter_hooks: ^0.17.0
  fl_chart: ^0.36.1
  flutter_svg: ^0.22.0
  uuid: ^3.0.4
  flutter_colorpicker: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/habit_icons/
